//
//  DataStoreConfiguration.h
//  Progress
//
//  Created by Sudhir Sawarkar on 10/27/15.
//  Copyright © 2015 Catamaran Labs. All rights reserved.
//

#ifndef DataStoreConfiguration_h
#define DataStoreConfiguration_h

// Global Defines
#define CHOICE_SELECTED__BOTTOM_LEFT    (1)
#define CHOICE_SELECTED__BOTTOM_RIGHT   (2)
#define CHOICE_SELECTED__BOTTOM_MIDDLE  (3)
#define CHOICE_SELECTED__TOP_LEFT       (4)
#define CHOICE_SELECTED__TOP_RIGHT      (5)
#define CHOICE_SELECTED__TOP_MIDDLE     (6)

#define LVL_IMAGES_CATEGORY__TYPE_COUNT       (4)
#define LVL_IMAGES_CATEGORY__SUB_TYPE_COUNT   (8)
#define LVL_IMAGES_CATEGORY__COLOR_COUNT      (7)

#define LVL_PLAYED__ONE_ONE           (11)
#define LVL_PLAYED__ONE_TWO           (12)
#define LVL_PLAYED__ONE_THREE         (13)
#define LVL_PLAYED__TWO_ONE           (21)
#define LVL_PLAYED__TWO_TWO           (22)
#define LVL_PLAYED__THREE_ONE         (31)
#define LVL_PLAYED__THREE_TWO         (32)

#define CHOICE_SELECTED_IMAGE_STR__WRONG       ("/wrong")
#define CHOICE_SELECTED_IMAGE_STR__RIGHT       ("/right")
#define CHOICE_SELECTED_IMAGE_STR__CHOICE      ("/choice")

// Level One - Beginner
#define LVL_ONE__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_ONE__CHOICE_BUTTON_TOTAL_COUNT  (2)

#define LVL_ONE__REWARD_FAST_TIMER_ADD_MS    (1000)
#define LVL_ONE__REWARD_NORMAL_TIMER_ADD_MS  (500)
#define LVL_ONE__REWARD_SLOW_TIMER_ADD_MS    (0)
#define LVL_ONE__REWARD_WRONG_TIMER_ADD_MS   (-1000)

#define LVL_ONE__RESPONSE_FAST_TIMER_ADD_MS    (700)
#define LVL_ONE__RESPONSE_NORMAL_TIMER_ADD_MS  (1200)
#define LVL_ONE__RESPONSE_SLOW_TIMER_ADD_MS    (1800)

#define LVL_ONE__RESPONSE_WRONG_TIMER_SUBSTRACT_MS (1000)

// Level Two - Intermediate
#define LVL_TWO__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_TWO__CHOICE_BUTTON_TOTAL_COUNT  (3)

#define LVL_TWO__REWARD_FAST_TIMER_ADD_MS    (1000)
#define LVL_TWO__REWARD_NORMAL_TIMER_ADD_MS  (500)
#define LVL_TWO__REWARD_SLOW_TIMER_ADD_MS    (0)
#define LVL_TWO__REWARD_WRONG_TIMER_ADD_MS   (-1000)

#define LVL_TWO__RESPONSE_FAST_TIMER_ADD_MS    (700)
#define LVL_TWO__RESPONSE_NORMAL_TIMER_ADD_MS  (1200)
#define LVL_TWO__RESPONSE_SLOW_TIMER_ADD_MS    (1800)

#define LVL_TWO__RESPONSE_WRONG_TIMER_SUBSTRACT_MS (1000)

// Level Three - Expert
#define LVL_THREE__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_THREE__CHOICE_BUTTON_TOTAL_COUNT  (4)

#define LVL_THREE__REWARD_FAST_TIMER_ADD_MS    (1000)
#define LVL_THREE__REWARD_NORMAL_TIMER_ADD_MS  (500)
#define LVL_THREE__REWARD_SLOW_TIMER_ADD_MS    (0)
#define LVL_THREE__REWARD_WRONG_TIMER_ADD_MS   (-1000)

#define LVL_THREE__RESPONSE_FAST_TIMER_ADD_MS    (700)
#define LVL_THREE__RESPONSE_NORMAL_TIMER_ADD_MS  (1200)
#define LVL_THREE__RESPONSE_SLOW_TIMER_ADD_MS    (1800)

#define LVL_THREE__RESPONSE_WRONG_TIMER_SUBSTRACT_MS (1000)


// Level Three - Expert
#define LVL_TWO_ONE__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_TWO_ONE__CHOICE_BUTTON_TOTAL_COUNT  (7)
#define LVL_TWO_ONE__IMAGE_REFERENT_TOTAL_COUNT (2)

#define LVL_TWO_TWO__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_TWO_TWO__CHOICE_BUTTON_TOTAL_COUNT  (11)
#define LVL_TWO_TWO__IMAGE_REFERENT_TOTAL_COUNT (2)

#define LVL_TWO__REWARD_FAST_TIMER_ADD_MS    (1000)
#define LVL_TWO__REWARD_NORMAL_TIMER_ADD_MS  (500)
#define LVL_TWO__REWARD_SLOW_TIMER_ADD_MS    (0)
#define LVL_TWO__REWARD_WRONG_TIMER_ADD_MS   (-1000)

#define LVL_TWO__RESPONSE_FAST_TIMER_ADD_MS    (700)
#define LVL_TWO__RESPONSE_NORMAL_TIMER_ADD_MS  (1200)
#define LVL_TWO__RESPONSE_SLOW_TIMER_ADD_MS    (1800)

#define LVL_TWO__RESPONSE_WRONG_TIMER_SUBSTRACT_MS (1000)

// Level Three - Expert
#define LVL_THREE_ONE__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_THREE_ONE__CHOICE_BUTTON_TOTAL_COUNT  (8)
#define LVL_THREE_ONE__IMAGE_REFERENT_TOTAL_COUNT (3)

#define LVL_THREE_TWO__PUZZLES_PER_LEVEL_MAX      (10)
#define LVL_THREE_TWO__CHOICE_BUTTON_TOTAL_COUNT  (10)
#define LVL_THREE_TWO__IMAGE_REFERENT_TOTAL_COUNT (5)

#define LVL_THREE__REWARD_FAST_TIMER_ADD_MS    (1000)
#define LVL_THREE__REWARD_NORMAL_TIMER_ADD_MS  (500)
#define LVL_THREE__REWARD_SLOW_TIMER_ADD_MS    (0)
#define LVL_THREE__REWARD_WRONG_TIMER_ADD_MS   (-1000)

#define LVL_THREE__RESPONSE_FAST_TIMER_ADD_MS    (700)
#define LVL_THREE__RESPONSE_NORMAL_TIMER_ADD_MS  (1200)
#define LVL_THREE__RESPONSE_SLOW_TIMER_ADD_MS    (1800)

#define LVL_THREE__RESPONSE_WRONG_TIMER_SUBSTRACT_MS (1000)


//
#define DEFAULT_EMPTY__STR       @" "
#define DEFAULT_TIME_LEFT_STR    @"100"
#define DEFAULT_BACK_BUTTON_STR  @"   Back"
#define DEFAULT_PLAYER_NAME_STR  @"Astronaut"

#define DEFAULT_CURR_MILLISECOND_LEFT_MS           (10000) // 10 seconds
#define LVL_TWO_DEFAULT_CURR_MILLISECOND_LEFT_MS   (15000) // 15 seconds
#define LVL_THREE_DEFAULT_CURR_MILLISECOND_LEFT_MS (35000) // 35 seconds

#endif /* DataStoreConfiguration_h */
